apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: # TODO: change this to your user number

resources:
- dev/
- prod/ 
- database-vm-import-source.yaml
- winweb01-vm-import-source.yaml
- winweb02-vm-import-source.yaml