apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitops-user6

resources:
- dev/
- prod/ 
- database-vm-import-source.yaml
- winweb01-vm-import-source.yaml
- winweb02-vm-import-source.yaml